CREATE SCHEMA webapp;

CREATE TABLE intexsoft.webapp.ROLES(
  ID SERIAL PRIMARY KEY ,
  TITLE VARCHAR(100) NOT NULL,
  CHECK (TITLE IN ('ROLE_ADMIN', 'ROLE_USER', 'ROLE_GUEST'))
);
CREATE TABLE intexsoft.webapp.USERS
(
    ID SERIAL PRIMARY KEY NOT NULL,
    FULLNAME VARCHAR(255) NOT NULL,
    LOGIN VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE_ID INTEGER NOT NULL ,
    FOREIGN KEY (ROLE_ID) REFERENCES intexsoft.webapp.ROLES(ID)
);
CREATE TABLE intexsoft.webapp.LINKS
(
  ID SERIAL PRIMARY KEY,
  URL VARCHAR(255) NOT NULL,
  SHORT_URL VARCHAR(100),
  DESCRIPTION VARCHAR(255),
  CLICK_AMOUNT INTEGER DEFAULT 0
);
CREATE TABLE intexsoft.webapp.TAGS
(
  ID SERIAL PRIMARY KEY,
  TITLE varchar(255) NOT NULL
);
CREATE TABLE intexsoft.webapp.LINKS_TAGS
(
  LINK_ID INTEGER NOT NULL ,
  TAG_ID INTEGER NOT NULL ,
  FOREIGN KEY (LINK_ID) REFERENCES intexsoft.webapp.LINKS (ID),
  FOREIGN KEY (TAG_ID) REFERENCES intexsoft.webapp.TAGS (ID)
);
CREATE TABLE intexsoft.webapp.USERS_LINKS
(
  USER_ID INTEGER NOT NULL ,
  LINK_ID INTEGER NOT NULL ,
  FOREIGN KEY (LINK_ID) REFERENCES intexsoft.webapp.links (ID),
  FOREIGN KEY (USER_ID) REFERENCES intexsoft.webapp.users (ID)
);


